/*
 * Problem 389: Find the Difference
 * Difficulty: Easy
 *
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 *      Input:
 *          s = "abcd"
 *          t = "abcde"
 * 
 *      Output:
 *          e
 * 
 * Explanation: 'e' is the letter that was added.
 */

namespace CSharpProblems
{
    public class Problem_389
    {
        public class Solution
        {
            public char FindTheDifference(string s, string t)
            {
                int[] freq = new int[26];
                for (int i = 0; i < s.Length; i++)
                {
                    freq[s[i] - 'a']++;
                }

                for (int i = 0; i < t.Length; i++)
                {
                    freq[t[i] - 'a']--;
                }

                for (int i = 0; i < freq.Length; i++)
                {
                    if (freq[i] != 0)
                    {
                        return (char)(i + 'a');
                    }
                }

                return ' ';
            }
        }
    }
}

/*
 * Complexity Analysis:
 * 		Time complexity : 
 * 		Space complexity: 
 */
